### ISSUE TITLE
Configurable Auto-Toggle Visibility Geofence distance

### ISSUE THREAD

**Issue by Matsuo3rd** [mKeRix/room-assistant-companion-ios#7]
Hello,

First of all thank you very much for your great software. It is really helpful for my home automation setup and works great to detect iPhone presence using BLE.

I would like to leverage your app in order to trigger Auto Unlock feature of my door lock upon arrival of someone.
However, with Auto-Toggle Visibility on, home status is reflected too late by the iPhone (once I am actually in home after having open the door manually). My understanding is that Auto Toggle Visibility feature was turned on too late as geofence radius might be extremely short. Do you happen to know what is the actual radius?

My ask is to make the Auto Toggle Visibility geofence distance configurable or using the same one as HomeKit uses for geofence trigger (someone leave/arrive home) as they work great for such purpose.

And again, thank you so much for sharing your great work.
Bertrand

**Comment by mKeRix** [comment]
Currently, the auto toggle visibility feature reacts on BLE beacons that the room-assistant instances send out. It does not utilize actual GPS data in any way. The feature is a bit broken atm for a few reasons though, which is why I wanted to rewrite it at some point. I haven't really decided on the best way for handling this yet though.

Maybe I can remove the native auto-toggling functionality and instead just integrate with the Shortcuts app? I think that should allow people to pretty much build any auto toggling they want.

**Comment by townsmcp** [comment]
@Matsuo3rd ive got this nailed to a T.
I have an AppleTV to take care of HomeKit.
Home Assistant is pushing devices to HomeKit.
Each person has a binary sensor for the actual presence. 
Each person has an input boolean.
Automation in HomeKit turns the input boolean on/off by geofencing.
HA automation changes the binary sensor state depending on the input boolean state.
NodeRed monitors the binary sensor. On state change to On, wait until the BLE RoomAssistant state changes to Home. Timeout after 10 minutes. Drop duplicates from all people input.
Unlock Danalock.
![FE79D730-A984-4338-9AE7-94FAC63278F8](https://user-images.githubusercontent.com/14061617/158079373-23cb71d5-d6e6-40bf-a69b-e3733a5ae151.jpeg)

Just an fyi, the RA RPI is about 1m away from the front door.
This all works in near real time. I highly recommend using the latest beta as the RA install. The latest official release didn’t work anywhere near as good - devices mostly took 10 minutes to register home in RA, but the beta is near real time (perhaps 5 second delay at most)

**Comment by Matsuo3rd** [comment]
> Maybe I can remove the native auto-toggling functionality and instead just integrate with the Shortcuts app? I think that should allow people to pretty much build any auto toggling they want.

@mKeRix: I would rather prefer geofence automation as it is completely silent/automatic. As far as I know Shortcut remains tricky in terms of full automation not requesting end user to perform any manual step (eg. clicking on a notification).

@townsmcp: your use case is exactly matching mine! I think you came down the same path as I did: Danalock auto unlock feature is quite sloppy. Thanks for sharing! Sorry to go off rails initial topic, but I have some questions/thoughts (and sorry for the long text):

1. My point was to save iPhones battery (if RA App overhead actually drains more power) by preventing them from sending BLE signal from room-assistant app when not needed (ie. outside my home geofence). I am willing to also cover use case when I get the trash downstairs (no leaving home geofence) and get home status detection so it unlocks the door when I get back. So that means that the RA App shall always send beacon when I am around my home. Btw: my European door has no handle on the outside panel - so a key is always needed to open if from the outside. That's where Danalock's "Hold back latch" feature comes handy.
2. Why are you using NodeRed? I use openHab (you could do the same with Home Assistant) that reacts upon room-assistant MQTT state change in order to trigger Danalock unlock command. This is also near real time.
3. Do you think you comment on using RA beta instead of master is still valid? Looking at RA GitHub repository branches commit: beta is lagging 6-Month behind master.
4. Going extreme, I also want to cover use case when I go for a run with Apple Watch only (no iPhone) and get the back home/auto unlock workflow working. I suppose you use BT Classic for your Apple Watch. People are reporting significant battery drain. Don't you? My plan is to use a sensor on my front door to get who is actually home/away (without false positive). When door is opened BT Classic is activated (through RA Inquiries Switch to ON). Inquiries Switch remains ON until door closes + 60 seconds (so I have time to leave BT radius). This shall be a large enough time window for detecting Apple Watch presence status change.If Apple Watch left home then keep Inquiries Switch ON (to detect when Apple Watch comes back), else turn RA Inquiries Switch OFF.  That shall optimize dramatically Apple Watch battery drain.  Would also be great to have the RA Inquiries Switch ability to be turned off at the device level (when running BT Classic with 2+ devices).
5. Also, BT Classic imposes a 10 seconds in between each scan (4 watches = 40 seconds lead time in worst case scenario). Going wild I am planning to have 2 additional BT dongles attached to my RPI (1 for BLE/iPhone + 1 for BT Classic / Apple Watch Classic + 1 for my daughter iPhone 6 running iOS 12/not supporting RA App). Running 2 BT Classic RA Integrations (with different hci devices) in parallel would reduce the 10 seconds lead time factor. But ... RA does not allow you to run the same Integration twice or more. Workaround: I can run multiple room-assistant instances.

I am looking forward to reading your thoughts on this.

**Comment by Matsuo3rd** [comment]
Closing issue.
For those interested: I moved to ESPresense (https://github.com/ESPresense/ESPresense) with a GL-iNet S10 hardware.
This covers perfectly my uses cases with both iPhones + Apple Watch.
